//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApprovalMGT
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", ConfigurationName="ApprovalMGT.PortalApprovalManager_Port")]
    public interface PortalApprovalManager_Port
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager:ApproveLeaveApplica" +
            "tion", ReplyAction="*")]
        System.Threading.Tasks.Task<ApprovalMGT.ApproveLeaveApplication_Result> ApproveLeaveApplicationAsync(ApprovalMGT.ApproveLeaveApplication request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager:RejectLeaveApplicat" +
            "ion", ReplyAction="*")]
        System.Threading.Tasks.Task<ApprovalMGT.RejectLeaveApplication_Result> RejectLeaveApplicationAsync(ApprovalMGT.RejectLeaveApplication request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager:RejectDocumentWithC" +
            "omments", ReplyAction="*")]
        System.Threading.Tasks.Task<ApprovalMGT.RejectDocumentWithComments_Result> RejectDocumentWithCommentsAsync(ApprovalMGT.RejectDocumentWithComments request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager:ApproveImprestAppli" +
            "cation", ReplyAction="*")]
        System.Threading.Tasks.Task<ApprovalMGT.ApproveImprestApplication_Result> ApproveImprestApplicationAsync(ApprovalMGT.ApproveImprestApplication request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager:RejectImprestApplic" +
            "ation", ReplyAction="*")]
        System.Threading.Tasks.Task<ApprovalMGT.RejectImprestApplication_Result> RejectImprestApplicationAsync(ApprovalMGT.RejectImprestApplication request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager:ApproveImprestAccou" +
            "nting", ReplyAction="*")]
        System.Threading.Tasks.Task<ApprovalMGT.ApproveImprestAccounting_Result> ApproveImprestAccountingAsync(ApprovalMGT.ApproveImprestAccounting request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager:RejectImprestAccoun" +
            "ting", ReplyAction="*")]
        System.Threading.Tasks.Task<ApprovalMGT.RejectImprestAccounting_Result> RejectImprestAccountingAsync(ApprovalMGT.RejectImprestAccounting request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager:ApproveStoreRequisi" +
            "tion", ReplyAction="*")]
        System.Threading.Tasks.Task<ApprovalMGT.ApproveStoreRequisition_Result> ApproveStoreRequisitionAsync(ApprovalMGT.ApproveStoreRequisition request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager:RejectStoreRequisit" +
            "ion", ReplyAction="*")]
        System.Threading.Tasks.Task<ApprovalMGT.RejectStoreRequisition_Result> RejectStoreRequisitionAsync(ApprovalMGT.RejectStoreRequisition request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager:ApprovePurchaseRequ" +
            "isition", ReplyAction="*")]
        System.Threading.Tasks.Task<ApprovalMGT.ApprovePurchaseRequisition_Result> ApprovePurchaseRequisitionAsync(ApprovalMGT.ApprovePurchaseRequisition request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager:RejectPurchaseRequi" +
            "sition", ReplyAction="*")]
        System.Threading.Tasks.Task<ApprovalMGT.RejectPurchaseRequisition_Result> RejectPurchaseRequisitionAsync(ApprovalMGT.RejectPurchaseRequisition request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager:ApproveTrainingAppl" +
            "ication", ReplyAction="*")]
        System.Threading.Tasks.Task<ApprovalMGT.ApproveTrainingApplication_Result> ApproveTrainingApplicationAsync(ApprovalMGT.ApproveTrainingApplication request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager:RejectTrainingAppli" +
            "cation", ReplyAction="*")]
        System.Threading.Tasks.Task<ApprovalMGT.RejectTrainingApplication_Result> RejectTrainingApplicationAsync(ApprovalMGT.RejectTrainingApplication request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager:ApproveTrainingNeed" +
            "", ReplyAction="*")]
        System.Threading.Tasks.Task<ApprovalMGT.ApproveTrainingNeed_Result> ApproveTrainingNeedAsync(ApprovalMGT.ApproveTrainingNeed request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager:RejectStoreTraining" +
            "Need", ReplyAction="*")]
        System.Threading.Tasks.Task<ApprovalMGT.RejectStoreTrainingNeed_Result> RejectStoreTrainingNeedAsync(ApprovalMGT.RejectStoreTrainingNeed request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager:ApproveTrainingEval" +
            "uation", ReplyAction="*")]
        System.Threading.Tasks.Task<ApprovalMGT.ApproveTrainingEvaluation_Result> ApproveTrainingEvaluationAsync(ApprovalMGT.ApproveTrainingEvaluation request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager:RejectStoreTraining" +
            "Evaluation", ReplyAction="*")]
        System.Threading.Tasks.Task<ApprovalMGT.RejectStoreTrainingEvaluation_Result> RejectStoreTrainingEvaluationAsync(ApprovalMGT.RejectStoreTrainingEvaluation request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager:RejectionComments", ReplyAction="*")]
        System.Threading.Tasks.Task<ApprovalMGT.RejectionComments_Result> RejectionCommentsAsync(ApprovalMGT.RejectionComments request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager:GetApprovalEntriesA" +
            "PI", ReplyAction="*")]
        System.Threading.Tasks.Task<ApprovalMGT.GetApprovalEntriesAPI_Result> GetApprovalEntriesAPIAsync(ApprovalMGT.GetApprovalEntriesAPI request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager:GetApprovalEntries", ReplyAction="*")]
        System.Threading.Tasks.Task<ApprovalMGT.GetApprovalEntries_Result> GetApprovalEntriesAsync(ApprovalMGT.GetApprovalEntries request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ApproveLeaveApplication", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", IsWrapped=true)]
    public partial class ApproveLeaveApplication
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", Order=0)]
        public string employeeNoa46;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", Order=1)]
        public string documentNoa46;
        
        public ApproveLeaveApplication()
        {
        }
        
        public ApproveLeaveApplication(string employeeNoa46, string documentNoa46)
        {
            this.employeeNoa46 = employeeNoa46;
            this.documentNoa46 = documentNoa46;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ApproveLeaveApplication_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", IsWrapped=true)]
    public partial class ApproveLeaveApplication_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", Order=0)]
        public bool return_value;
        
        public ApproveLeaveApplication_Result()
        {
        }
        
        public ApproveLeaveApplication_Result(bool return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RejectLeaveApplication", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", IsWrapped=true)]
    public partial class RejectLeaveApplication
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", Order=0)]
        public string employeeNoa46;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", Order=1)]
        public string documentNoa46;
        
        public RejectLeaveApplication()
        {
        }
        
        public RejectLeaveApplication(string employeeNoa46, string documentNoa46)
        {
            this.employeeNoa46 = employeeNoa46;
            this.documentNoa46 = documentNoa46;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RejectLeaveApplication_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", IsWrapped=true)]
    public partial class RejectLeaveApplication_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", Order=0)]
        public bool return_value;
        
        public RejectLeaveApplication_Result()
        {
        }
        
        public RejectLeaveApplication_Result(bool return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RejectDocumentWithComments", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", IsWrapped=true)]
    public partial class RejectDocumentWithComments
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", Order=0)]
        public string employeeNoa46;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", Order=1)]
        public string documentNoa46;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", Order=2)]
        public string rejectionComments;
        
        public RejectDocumentWithComments()
        {
        }
        
        public RejectDocumentWithComments(string employeeNoa46, string documentNoa46, string rejectionComments)
        {
            this.employeeNoa46 = employeeNoa46;
            this.documentNoa46 = documentNoa46;
            this.rejectionComments = rejectionComments;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RejectDocumentWithComments_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", IsWrapped=true)]
    public partial class RejectDocumentWithComments_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", Order=0)]
        public bool return_value;
        
        public RejectDocumentWithComments_Result()
        {
        }
        
        public RejectDocumentWithComments_Result(bool return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ApproveImprestApplication", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", IsWrapped=true)]
    public partial class ApproveImprestApplication
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", Order=0)]
        public string employeeNoa46;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", Order=1)]
        public string documentNoa46;
        
        public ApproveImprestApplication()
        {
        }
        
        public ApproveImprestApplication(string employeeNoa46, string documentNoa46)
        {
            this.employeeNoa46 = employeeNoa46;
            this.documentNoa46 = documentNoa46;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ApproveImprestApplication_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", IsWrapped=true)]
    public partial class ApproveImprestApplication_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", Order=0)]
        public bool return_value;
        
        public ApproveImprestApplication_Result()
        {
        }
        
        public ApproveImprestApplication_Result(bool return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RejectImprestApplication", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", IsWrapped=true)]
    public partial class RejectImprestApplication
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", Order=0)]
        public string employeeNoa46;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", Order=1)]
        public string documentNoa46;
        
        public RejectImprestApplication()
        {
        }
        
        public RejectImprestApplication(string employeeNoa46, string documentNoa46)
        {
            this.employeeNoa46 = employeeNoa46;
            this.documentNoa46 = documentNoa46;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RejectImprestApplication_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", IsWrapped=true)]
    public partial class RejectImprestApplication_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", Order=0)]
        public bool return_value;
        
        public RejectImprestApplication_Result()
        {
        }
        
        public RejectImprestApplication_Result(bool return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ApproveImprestAccounting", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", IsWrapped=true)]
    public partial class ApproveImprestAccounting
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", Order=0)]
        public string employeeNoa46;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", Order=1)]
        public string documentNoa46;
        
        public ApproveImprestAccounting()
        {
        }
        
        public ApproveImprestAccounting(string employeeNoa46, string documentNoa46)
        {
            this.employeeNoa46 = employeeNoa46;
            this.documentNoa46 = documentNoa46;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ApproveImprestAccounting_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", IsWrapped=true)]
    public partial class ApproveImprestAccounting_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", Order=0)]
        public bool return_value;
        
        public ApproveImprestAccounting_Result()
        {
        }
        
        public ApproveImprestAccounting_Result(bool return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RejectImprestAccounting", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", IsWrapped=true)]
    public partial class RejectImprestAccounting
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", Order=0)]
        public string employeeNoa46;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", Order=1)]
        public string documentNoa46;
        
        public RejectImprestAccounting()
        {
        }
        
        public RejectImprestAccounting(string employeeNoa46, string documentNoa46)
        {
            this.employeeNoa46 = employeeNoa46;
            this.documentNoa46 = documentNoa46;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RejectImprestAccounting_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", IsWrapped=true)]
    public partial class RejectImprestAccounting_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", Order=0)]
        public bool return_value;
        
        public RejectImprestAccounting_Result()
        {
        }
        
        public RejectImprestAccounting_Result(bool return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ApproveStoreRequisition", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", IsWrapped=true)]
    public partial class ApproveStoreRequisition
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", Order=0)]
        public string employeeNoa46;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", Order=1)]
        public string documentNoa46;
        
        public ApproveStoreRequisition()
        {
        }
        
        public ApproveStoreRequisition(string employeeNoa46, string documentNoa46)
        {
            this.employeeNoa46 = employeeNoa46;
            this.documentNoa46 = documentNoa46;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ApproveStoreRequisition_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", IsWrapped=true)]
    public partial class ApproveStoreRequisition_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", Order=0)]
        public bool return_value;
        
        public ApproveStoreRequisition_Result()
        {
        }
        
        public ApproveStoreRequisition_Result(bool return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RejectStoreRequisition", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", IsWrapped=true)]
    public partial class RejectStoreRequisition
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", Order=0)]
        public string employeeNoa46;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", Order=1)]
        public string documentNoa46;
        
        public RejectStoreRequisition()
        {
        }
        
        public RejectStoreRequisition(string employeeNoa46, string documentNoa46)
        {
            this.employeeNoa46 = employeeNoa46;
            this.documentNoa46 = documentNoa46;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RejectStoreRequisition_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", IsWrapped=true)]
    public partial class RejectStoreRequisition_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", Order=0)]
        public bool return_value;
        
        public RejectStoreRequisition_Result()
        {
        }
        
        public RejectStoreRequisition_Result(bool return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ApprovePurchaseRequisition", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", IsWrapped=true)]
    public partial class ApprovePurchaseRequisition
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", Order=0)]
        public string employeeNoa46;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", Order=1)]
        public string documentNoa46;
        
        public ApprovePurchaseRequisition()
        {
        }
        
        public ApprovePurchaseRequisition(string employeeNoa46, string documentNoa46)
        {
            this.employeeNoa46 = employeeNoa46;
            this.documentNoa46 = documentNoa46;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ApprovePurchaseRequisition_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", IsWrapped=true)]
    public partial class ApprovePurchaseRequisition_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", Order=0)]
        public bool return_value;
        
        public ApprovePurchaseRequisition_Result()
        {
        }
        
        public ApprovePurchaseRequisition_Result(bool return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RejectPurchaseRequisition", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", IsWrapped=true)]
    public partial class RejectPurchaseRequisition
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", Order=0)]
        public string employeeNoa46;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", Order=1)]
        public string documentNoa46;
        
        public RejectPurchaseRequisition()
        {
        }
        
        public RejectPurchaseRequisition(string employeeNoa46, string documentNoa46)
        {
            this.employeeNoa46 = employeeNoa46;
            this.documentNoa46 = documentNoa46;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RejectPurchaseRequisition_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", IsWrapped=true)]
    public partial class RejectPurchaseRequisition_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", Order=0)]
        public bool return_value;
        
        public RejectPurchaseRequisition_Result()
        {
        }
        
        public RejectPurchaseRequisition_Result(bool return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ApproveTrainingApplication", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", IsWrapped=true)]
    public partial class ApproveTrainingApplication
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", Order=0)]
        public string employeeNoa46;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", Order=1)]
        public string documentNoa46;
        
        public ApproveTrainingApplication()
        {
        }
        
        public ApproveTrainingApplication(string employeeNoa46, string documentNoa46)
        {
            this.employeeNoa46 = employeeNoa46;
            this.documentNoa46 = documentNoa46;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ApproveTrainingApplication_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", IsWrapped=true)]
    public partial class ApproveTrainingApplication_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", Order=0)]
        public bool return_value;
        
        public ApproveTrainingApplication_Result()
        {
        }
        
        public ApproveTrainingApplication_Result(bool return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RejectTrainingApplication", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", IsWrapped=true)]
    public partial class RejectTrainingApplication
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", Order=0)]
        public string employeeNoa46;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", Order=1)]
        public string documentNoa46;
        
        public RejectTrainingApplication()
        {
        }
        
        public RejectTrainingApplication(string employeeNoa46, string documentNoa46)
        {
            this.employeeNoa46 = employeeNoa46;
            this.documentNoa46 = documentNoa46;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RejectTrainingApplication_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", IsWrapped=true)]
    public partial class RejectTrainingApplication_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", Order=0)]
        public bool return_value;
        
        public RejectTrainingApplication_Result()
        {
        }
        
        public RejectTrainingApplication_Result(bool return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ApproveTrainingNeed", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", IsWrapped=true)]
    public partial class ApproveTrainingNeed
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", Order=0)]
        public string employeeNoa46;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", Order=1)]
        public string documentNoa46;
        
        public ApproveTrainingNeed()
        {
        }
        
        public ApproveTrainingNeed(string employeeNoa46, string documentNoa46)
        {
            this.employeeNoa46 = employeeNoa46;
            this.documentNoa46 = documentNoa46;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ApproveTrainingNeed_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", IsWrapped=true)]
    public partial class ApproveTrainingNeed_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", Order=0)]
        public bool return_value;
        
        public ApproveTrainingNeed_Result()
        {
        }
        
        public ApproveTrainingNeed_Result(bool return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RejectStoreTrainingNeed", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", IsWrapped=true)]
    public partial class RejectStoreTrainingNeed
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", Order=0)]
        public string employeeNoa46;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", Order=1)]
        public string documentNoa46;
        
        public RejectStoreTrainingNeed()
        {
        }
        
        public RejectStoreTrainingNeed(string employeeNoa46, string documentNoa46)
        {
            this.employeeNoa46 = employeeNoa46;
            this.documentNoa46 = documentNoa46;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RejectStoreTrainingNeed_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", IsWrapped=true)]
    public partial class RejectStoreTrainingNeed_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", Order=0)]
        public bool return_value;
        
        public RejectStoreTrainingNeed_Result()
        {
        }
        
        public RejectStoreTrainingNeed_Result(bool return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ApproveTrainingEvaluation", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", IsWrapped=true)]
    public partial class ApproveTrainingEvaluation
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", Order=0)]
        public string employeeNoa46;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", Order=1)]
        public string documentNoa46;
        
        public ApproveTrainingEvaluation()
        {
        }
        
        public ApproveTrainingEvaluation(string employeeNoa46, string documentNoa46)
        {
            this.employeeNoa46 = employeeNoa46;
            this.documentNoa46 = documentNoa46;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ApproveTrainingEvaluation_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", IsWrapped=true)]
    public partial class ApproveTrainingEvaluation_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", Order=0)]
        public bool return_value;
        
        public ApproveTrainingEvaluation_Result()
        {
        }
        
        public ApproveTrainingEvaluation_Result(bool return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RejectStoreTrainingEvaluation", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", IsWrapped=true)]
    public partial class RejectStoreTrainingEvaluation
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", Order=0)]
        public string employeeNoa46;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", Order=1)]
        public string documentNoa46;
        
        public RejectStoreTrainingEvaluation()
        {
        }
        
        public RejectStoreTrainingEvaluation(string employeeNoa46, string documentNoa46)
        {
            this.employeeNoa46 = employeeNoa46;
            this.documentNoa46 = documentNoa46;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RejectStoreTrainingEvaluation_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", IsWrapped=true)]
    public partial class RejectStoreTrainingEvaluation_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", Order=0)]
        public bool return_value;
        
        public RejectStoreTrainingEvaluation_Result()
        {
        }
        
        public RejectStoreTrainingEvaluation_Result(bool return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RejectionComments", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", IsWrapped=true)]
    public partial class RejectionComments
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", Order=0)]
        public string documentNo;
        
        public RejectionComments()
        {
        }
        
        public RejectionComments(string documentNo)
        {
            this.documentNo = documentNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RejectionComments_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", IsWrapped=true)]
    public partial class RejectionComments_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", Order=0)]
        public string return_value;
        
        public RejectionComments_Result()
        {
        }
        
        public RejectionComments_Result(string return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetApprovalEntriesAPI", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", IsWrapped=true)]
    public partial class GetApprovalEntriesAPI
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", Order=0)]
        public string employeeNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", Order=1)]
        public string documentNo;
        
        public GetApprovalEntriesAPI()
        {
        }
        
        public GetApprovalEntriesAPI(string employeeNo, string documentNo)
        {
            this.employeeNo = employeeNo;
            this.documentNo = documentNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetApprovalEntriesAPI_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", IsWrapped=true)]
    public partial class GetApprovalEntriesAPI_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", Order=0)]
        public string return_value;
        
        public GetApprovalEntriesAPI_Result()
        {
        }
        
        public GetApprovalEntriesAPI_Result(string return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetApprovalEntries", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", IsWrapped=true)]
    public partial class GetApprovalEntries
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", Order=0)]
        public string employeeNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", Order=1)]
        public string documentNo;
        
        public GetApprovalEntries()
        {
        }
        
        public GetApprovalEntries(string employeeNo, string documentNo)
        {
            this.employeeNo = employeeNo;
            this.documentNo = documentNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetApprovalEntries_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", IsWrapped=true)]
    public partial class GetApprovalEntries_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/PortalApprovalManager", Order=0)]
        public string return_value;
        
        public GetApprovalEntries_Result()
        {
        }
        
        public GetApprovalEntries_Result(string return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public interface PortalApprovalManager_PortChannel : ApprovalMGT.PortalApprovalManager_Port, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public partial class PortalApprovalManager_PortClient : System.ServiceModel.ClientBase<ApprovalMGT.PortalApprovalManager_Port>, ApprovalMGT.PortalApprovalManager_Port
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public PortalApprovalManager_PortClient() : 
                base(PortalApprovalManager_PortClient.GetDefaultBinding(), PortalApprovalManager_PortClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.PortalApprovalManager_Port.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PortalApprovalManager_PortClient(EndpointConfiguration endpointConfiguration) : 
                base(PortalApprovalManager_PortClient.GetBindingForEndpoint(endpointConfiguration), PortalApprovalManager_PortClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PortalApprovalManager_PortClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(PortalApprovalManager_PortClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PortalApprovalManager_PortClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(PortalApprovalManager_PortClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PortalApprovalManager_PortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ApprovalMGT.ApproveLeaveApplication_Result> ApprovalMGT.PortalApprovalManager_Port.ApproveLeaveApplicationAsync(ApprovalMGT.ApproveLeaveApplication request)
        {
            return base.Channel.ApproveLeaveApplicationAsync(request);
        }
        
        public System.Threading.Tasks.Task<ApprovalMGT.ApproveLeaveApplication_Result> ApproveLeaveApplicationAsync(string employeeNoa46, string documentNoa46)
        {
            ApprovalMGT.ApproveLeaveApplication inValue = new ApprovalMGT.ApproveLeaveApplication();
            inValue.employeeNoa46 = employeeNoa46;
            inValue.documentNoa46 = documentNoa46;
            return ((ApprovalMGT.PortalApprovalManager_Port)(this)).ApproveLeaveApplicationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ApprovalMGT.RejectLeaveApplication_Result> ApprovalMGT.PortalApprovalManager_Port.RejectLeaveApplicationAsync(ApprovalMGT.RejectLeaveApplication request)
        {
            return base.Channel.RejectLeaveApplicationAsync(request);
        }
        
        public System.Threading.Tasks.Task<ApprovalMGT.RejectLeaveApplication_Result> RejectLeaveApplicationAsync(string employeeNoa46, string documentNoa46)
        {
            ApprovalMGT.RejectLeaveApplication inValue = new ApprovalMGT.RejectLeaveApplication();
            inValue.employeeNoa46 = employeeNoa46;
            inValue.documentNoa46 = documentNoa46;
            return ((ApprovalMGT.PortalApprovalManager_Port)(this)).RejectLeaveApplicationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ApprovalMGT.RejectDocumentWithComments_Result> ApprovalMGT.PortalApprovalManager_Port.RejectDocumentWithCommentsAsync(ApprovalMGT.RejectDocumentWithComments request)
        {
            return base.Channel.RejectDocumentWithCommentsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ApprovalMGT.RejectDocumentWithComments_Result> RejectDocumentWithCommentsAsync(string employeeNoa46, string documentNoa46, string rejectionComments)
        {
            ApprovalMGT.RejectDocumentWithComments inValue = new ApprovalMGT.RejectDocumentWithComments();
            inValue.employeeNoa46 = employeeNoa46;
            inValue.documentNoa46 = documentNoa46;
            inValue.rejectionComments = rejectionComments;
            return ((ApprovalMGT.PortalApprovalManager_Port)(this)).RejectDocumentWithCommentsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ApprovalMGT.ApproveImprestApplication_Result> ApprovalMGT.PortalApprovalManager_Port.ApproveImprestApplicationAsync(ApprovalMGT.ApproveImprestApplication request)
        {
            return base.Channel.ApproveImprestApplicationAsync(request);
        }
        
        public System.Threading.Tasks.Task<ApprovalMGT.ApproveImprestApplication_Result> ApproveImprestApplicationAsync(string employeeNoa46, string documentNoa46)
        {
            ApprovalMGT.ApproveImprestApplication inValue = new ApprovalMGT.ApproveImprestApplication();
            inValue.employeeNoa46 = employeeNoa46;
            inValue.documentNoa46 = documentNoa46;
            return ((ApprovalMGT.PortalApprovalManager_Port)(this)).ApproveImprestApplicationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ApprovalMGT.RejectImprestApplication_Result> ApprovalMGT.PortalApprovalManager_Port.RejectImprestApplicationAsync(ApprovalMGT.RejectImprestApplication request)
        {
            return base.Channel.RejectImprestApplicationAsync(request);
        }
        
        public System.Threading.Tasks.Task<ApprovalMGT.RejectImprestApplication_Result> RejectImprestApplicationAsync(string employeeNoa46, string documentNoa46)
        {
            ApprovalMGT.RejectImprestApplication inValue = new ApprovalMGT.RejectImprestApplication();
            inValue.employeeNoa46 = employeeNoa46;
            inValue.documentNoa46 = documentNoa46;
            return ((ApprovalMGT.PortalApprovalManager_Port)(this)).RejectImprestApplicationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ApprovalMGT.ApproveImprestAccounting_Result> ApprovalMGT.PortalApprovalManager_Port.ApproveImprestAccountingAsync(ApprovalMGT.ApproveImprestAccounting request)
        {
            return base.Channel.ApproveImprestAccountingAsync(request);
        }
        
        public System.Threading.Tasks.Task<ApprovalMGT.ApproveImprestAccounting_Result> ApproveImprestAccountingAsync(string employeeNoa46, string documentNoa46)
        {
            ApprovalMGT.ApproveImprestAccounting inValue = new ApprovalMGT.ApproveImprestAccounting();
            inValue.employeeNoa46 = employeeNoa46;
            inValue.documentNoa46 = documentNoa46;
            return ((ApprovalMGT.PortalApprovalManager_Port)(this)).ApproveImprestAccountingAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ApprovalMGT.RejectImprestAccounting_Result> ApprovalMGT.PortalApprovalManager_Port.RejectImprestAccountingAsync(ApprovalMGT.RejectImprestAccounting request)
        {
            return base.Channel.RejectImprestAccountingAsync(request);
        }
        
        public System.Threading.Tasks.Task<ApprovalMGT.RejectImprestAccounting_Result> RejectImprestAccountingAsync(string employeeNoa46, string documentNoa46)
        {
            ApprovalMGT.RejectImprestAccounting inValue = new ApprovalMGT.RejectImprestAccounting();
            inValue.employeeNoa46 = employeeNoa46;
            inValue.documentNoa46 = documentNoa46;
            return ((ApprovalMGT.PortalApprovalManager_Port)(this)).RejectImprestAccountingAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ApprovalMGT.ApproveStoreRequisition_Result> ApprovalMGT.PortalApprovalManager_Port.ApproveStoreRequisitionAsync(ApprovalMGT.ApproveStoreRequisition request)
        {
            return base.Channel.ApproveStoreRequisitionAsync(request);
        }
        
        public System.Threading.Tasks.Task<ApprovalMGT.ApproveStoreRequisition_Result> ApproveStoreRequisitionAsync(string employeeNoa46, string documentNoa46)
        {
            ApprovalMGT.ApproveStoreRequisition inValue = new ApprovalMGT.ApproveStoreRequisition();
            inValue.employeeNoa46 = employeeNoa46;
            inValue.documentNoa46 = documentNoa46;
            return ((ApprovalMGT.PortalApprovalManager_Port)(this)).ApproveStoreRequisitionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ApprovalMGT.RejectStoreRequisition_Result> ApprovalMGT.PortalApprovalManager_Port.RejectStoreRequisitionAsync(ApprovalMGT.RejectStoreRequisition request)
        {
            return base.Channel.RejectStoreRequisitionAsync(request);
        }
        
        public System.Threading.Tasks.Task<ApprovalMGT.RejectStoreRequisition_Result> RejectStoreRequisitionAsync(string employeeNoa46, string documentNoa46)
        {
            ApprovalMGT.RejectStoreRequisition inValue = new ApprovalMGT.RejectStoreRequisition();
            inValue.employeeNoa46 = employeeNoa46;
            inValue.documentNoa46 = documentNoa46;
            return ((ApprovalMGT.PortalApprovalManager_Port)(this)).RejectStoreRequisitionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ApprovalMGT.ApprovePurchaseRequisition_Result> ApprovalMGT.PortalApprovalManager_Port.ApprovePurchaseRequisitionAsync(ApprovalMGT.ApprovePurchaseRequisition request)
        {
            return base.Channel.ApprovePurchaseRequisitionAsync(request);
        }
        
        public System.Threading.Tasks.Task<ApprovalMGT.ApprovePurchaseRequisition_Result> ApprovePurchaseRequisitionAsync(string employeeNoa46, string documentNoa46)
        {
            ApprovalMGT.ApprovePurchaseRequisition inValue = new ApprovalMGT.ApprovePurchaseRequisition();
            inValue.employeeNoa46 = employeeNoa46;
            inValue.documentNoa46 = documentNoa46;
            return ((ApprovalMGT.PortalApprovalManager_Port)(this)).ApprovePurchaseRequisitionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ApprovalMGT.RejectPurchaseRequisition_Result> ApprovalMGT.PortalApprovalManager_Port.RejectPurchaseRequisitionAsync(ApprovalMGT.RejectPurchaseRequisition request)
        {
            return base.Channel.RejectPurchaseRequisitionAsync(request);
        }
        
        public System.Threading.Tasks.Task<ApprovalMGT.RejectPurchaseRequisition_Result> RejectPurchaseRequisitionAsync(string employeeNoa46, string documentNoa46)
        {
            ApprovalMGT.RejectPurchaseRequisition inValue = new ApprovalMGT.RejectPurchaseRequisition();
            inValue.employeeNoa46 = employeeNoa46;
            inValue.documentNoa46 = documentNoa46;
            return ((ApprovalMGT.PortalApprovalManager_Port)(this)).RejectPurchaseRequisitionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ApprovalMGT.ApproveTrainingApplication_Result> ApprovalMGT.PortalApprovalManager_Port.ApproveTrainingApplicationAsync(ApprovalMGT.ApproveTrainingApplication request)
        {
            return base.Channel.ApproveTrainingApplicationAsync(request);
        }
        
        public System.Threading.Tasks.Task<ApprovalMGT.ApproveTrainingApplication_Result> ApproveTrainingApplicationAsync(string employeeNoa46, string documentNoa46)
        {
            ApprovalMGT.ApproveTrainingApplication inValue = new ApprovalMGT.ApproveTrainingApplication();
            inValue.employeeNoa46 = employeeNoa46;
            inValue.documentNoa46 = documentNoa46;
            return ((ApprovalMGT.PortalApprovalManager_Port)(this)).ApproveTrainingApplicationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ApprovalMGT.RejectTrainingApplication_Result> ApprovalMGT.PortalApprovalManager_Port.RejectTrainingApplicationAsync(ApprovalMGT.RejectTrainingApplication request)
        {
            return base.Channel.RejectTrainingApplicationAsync(request);
        }
        
        public System.Threading.Tasks.Task<ApprovalMGT.RejectTrainingApplication_Result> RejectTrainingApplicationAsync(string employeeNoa46, string documentNoa46)
        {
            ApprovalMGT.RejectTrainingApplication inValue = new ApprovalMGT.RejectTrainingApplication();
            inValue.employeeNoa46 = employeeNoa46;
            inValue.documentNoa46 = documentNoa46;
            return ((ApprovalMGT.PortalApprovalManager_Port)(this)).RejectTrainingApplicationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ApprovalMGT.ApproveTrainingNeed_Result> ApprovalMGT.PortalApprovalManager_Port.ApproveTrainingNeedAsync(ApprovalMGT.ApproveTrainingNeed request)
        {
            return base.Channel.ApproveTrainingNeedAsync(request);
        }
        
        public System.Threading.Tasks.Task<ApprovalMGT.ApproveTrainingNeed_Result> ApproveTrainingNeedAsync(string employeeNoa46, string documentNoa46)
        {
            ApprovalMGT.ApproveTrainingNeed inValue = new ApprovalMGT.ApproveTrainingNeed();
            inValue.employeeNoa46 = employeeNoa46;
            inValue.documentNoa46 = documentNoa46;
            return ((ApprovalMGT.PortalApprovalManager_Port)(this)).ApproveTrainingNeedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ApprovalMGT.RejectStoreTrainingNeed_Result> ApprovalMGT.PortalApprovalManager_Port.RejectStoreTrainingNeedAsync(ApprovalMGT.RejectStoreTrainingNeed request)
        {
            return base.Channel.RejectStoreTrainingNeedAsync(request);
        }
        
        public System.Threading.Tasks.Task<ApprovalMGT.RejectStoreTrainingNeed_Result> RejectStoreTrainingNeedAsync(string employeeNoa46, string documentNoa46)
        {
            ApprovalMGT.RejectStoreTrainingNeed inValue = new ApprovalMGT.RejectStoreTrainingNeed();
            inValue.employeeNoa46 = employeeNoa46;
            inValue.documentNoa46 = documentNoa46;
            return ((ApprovalMGT.PortalApprovalManager_Port)(this)).RejectStoreTrainingNeedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ApprovalMGT.ApproveTrainingEvaluation_Result> ApprovalMGT.PortalApprovalManager_Port.ApproveTrainingEvaluationAsync(ApprovalMGT.ApproveTrainingEvaluation request)
        {
            return base.Channel.ApproveTrainingEvaluationAsync(request);
        }
        
        public System.Threading.Tasks.Task<ApprovalMGT.ApproveTrainingEvaluation_Result> ApproveTrainingEvaluationAsync(string employeeNoa46, string documentNoa46)
        {
            ApprovalMGT.ApproveTrainingEvaluation inValue = new ApprovalMGT.ApproveTrainingEvaluation();
            inValue.employeeNoa46 = employeeNoa46;
            inValue.documentNoa46 = documentNoa46;
            return ((ApprovalMGT.PortalApprovalManager_Port)(this)).ApproveTrainingEvaluationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ApprovalMGT.RejectStoreTrainingEvaluation_Result> ApprovalMGT.PortalApprovalManager_Port.RejectStoreTrainingEvaluationAsync(ApprovalMGT.RejectStoreTrainingEvaluation request)
        {
            return base.Channel.RejectStoreTrainingEvaluationAsync(request);
        }
        
        public System.Threading.Tasks.Task<ApprovalMGT.RejectStoreTrainingEvaluation_Result> RejectStoreTrainingEvaluationAsync(string employeeNoa46, string documentNoa46)
        {
            ApprovalMGT.RejectStoreTrainingEvaluation inValue = new ApprovalMGT.RejectStoreTrainingEvaluation();
            inValue.employeeNoa46 = employeeNoa46;
            inValue.documentNoa46 = documentNoa46;
            return ((ApprovalMGT.PortalApprovalManager_Port)(this)).RejectStoreTrainingEvaluationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ApprovalMGT.RejectionComments_Result> ApprovalMGT.PortalApprovalManager_Port.RejectionCommentsAsync(ApprovalMGT.RejectionComments request)
        {
            return base.Channel.RejectionCommentsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ApprovalMGT.RejectionComments_Result> RejectionCommentsAsync(string documentNo)
        {
            ApprovalMGT.RejectionComments inValue = new ApprovalMGT.RejectionComments();
            inValue.documentNo = documentNo;
            return ((ApprovalMGT.PortalApprovalManager_Port)(this)).RejectionCommentsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ApprovalMGT.GetApprovalEntriesAPI_Result> ApprovalMGT.PortalApprovalManager_Port.GetApprovalEntriesAPIAsync(ApprovalMGT.GetApprovalEntriesAPI request)
        {
            return base.Channel.GetApprovalEntriesAPIAsync(request);
        }
        
        public System.Threading.Tasks.Task<ApprovalMGT.GetApprovalEntriesAPI_Result> GetApprovalEntriesAPIAsync(string employeeNo, string documentNo)
        {
            ApprovalMGT.GetApprovalEntriesAPI inValue = new ApprovalMGT.GetApprovalEntriesAPI();
            inValue.employeeNo = employeeNo;
            inValue.documentNo = documentNo;
            return ((ApprovalMGT.PortalApprovalManager_Port)(this)).GetApprovalEntriesAPIAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ApprovalMGT.GetApprovalEntries_Result> ApprovalMGT.PortalApprovalManager_Port.GetApprovalEntriesAsync(ApprovalMGT.GetApprovalEntries request)
        {
            return base.Channel.GetApprovalEntriesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ApprovalMGT.GetApprovalEntries_Result> GetApprovalEntriesAsync(string employeeNo, string documentNo)
        {
            ApprovalMGT.GetApprovalEntries inValue = new ApprovalMGT.GetApprovalEntries();
            inValue.employeeNo = employeeNo;
            inValue.documentNo = documentNo;
            return ((ApprovalMGT.PortalApprovalManager_Port)(this)).GetApprovalEntriesAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.PortalApprovalManager_Port))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.TransportCredentialOnly;
                result.Security.Transport.ClientCredentialType = System.ServiceModel.HttpClientCredentialType.Basic;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.PortalApprovalManager_Port))
            {
                return new System.ServiceModel.EndpointAddress("http://desktop-csglh1r:7347/PLATCORP/WS/Platcorp Training/Codeunit/PortalApproval" +
                        "Manager");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return PortalApprovalManager_PortClient.GetBindingForEndpoint(EndpointConfiguration.PortalApprovalManager_Port);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return PortalApprovalManager_PortClient.GetEndpointAddress(EndpointConfiguration.PortalApprovalManager_Port);
        }
        
        public enum EndpointConfiguration
        {
            
            PortalApprovalManager_Port,
        }
    }
}
